import { defineField, defineType } from 'sanity';

export const siteConfig = defineType({
  name: 'siteConfig',
  title: 'Business & Contact Information',
  type: 'document',
  groups: [
    { name: 'general', title: '🏢 General Details', default: true },
    { name: 'contact', title: '📞 Contact Numbers & Email' },
    { name: 'address', title: '📍 Physical Address' },
    { name: 'socials', title: '📱 Social Media Links' },
    { name: 'hours', title: '⏰ Operating Hours' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Business Brand Name',
      type: 'string',
      group: 'general',
      initialValue: 'Luxmi Flora Wedding & Events',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Brand Tagline',
      type: 'string',
      group: 'general',
      initialValue: 'Weddings · Floral · Events',
    }),
    defineField({
      name: 'description',
      title: 'Short Brand Description',
      type: 'text',
      group: 'general',
      initialValue: 'Transforming weddings and special occasions into unforgettable celebrations with elegant floral designs and beautifully crafted event décor.',
    }),
    defineField({
      name: 'phone',
      title: 'Main Business Phone Number',
      type: 'string',
      group: 'contact',
      initialValue: '0765495489',
    }),
    defineField({
      name: 'whatsappNumber',
      title: 'Business WhatsApp Number (without + or with standard international)',
      type: 'string',
      group: 'contact',
      initialValue: '0765495489',
    }),
    defineField({
      name: 'email',
      title: 'Primary Business Email Address',
      type: 'string',
      group: 'contact',
      initialValue: 'luxmiflora@gmail.com',
    }),
    defineField({
      name: 'address',
      title: 'Complete Business Physical Address',
      type: 'text',
      group: 'address',
      initialValue: 'Luxmi Flora Wedding & Events, No.45/8, Badulla road, Bandarawela, Sri Lanka',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'googleMapsUrl',
      title: 'Google Maps Link (Optional)',
      type: 'url',
      group: 'address',
    }),
    defineField({
      name: 'instagramUrl',
      title: 'Instagram Profile Link',
      type: 'url',
      group: 'socials',
      initialValue: 'https://www.instagram.com/luxmi_flora_wedding_and__event?igsi=bmNnZ3cwMnoxeTJr',
    }),
    defineField({
      name: 'facebookUrl',
      title: 'Facebook Page Link',
      type: 'url',
      group: 'socials',
      initialValue: 'https://www.facebook.com/share/18VsinLxD5/?mibextid=wwXIfr',
    }),
    defineField({
      name: 'tiktokUrl',
      title: 'TikTok Profile Link',
      type: 'url',
      group: 'socials',
      initialValue: 'https://www.tiktok.com/@luxmi_floraweddingevent?_r=1&_t=ZS-990vR65MV61',
    }),
    defineField({
      name: 'workingHours',
      title: 'Working Hours',
      type: 'string',
      group: 'hours',
      initialValue: 'Mon - Sat: 9:00 AM - 6:00 PM',
    }),
  ],
});
